version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
      - JWT_SECRET=sua_secret_key
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - backend-network

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge
